baseURL: "https://nyaacinth.moe/"
title: "Nyaacinth's Blog"
theme: "stack"
languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"
hasCJKLanguage: true
params:
    favicon: "static/avatar.jpg"
    rssFullContent: true
    sidebar:
        subtitle: "喵之声"
        avatar:
            enabled: true
            local: true
            src: "avatar.jpg"
